export enum Genre {
  ACTION = "Action",
  AVENTURE = "Aventure",
  DRAMA = "Drame",
  SURNATURAL = "Surnaturel",
  HORROR = "Horreur",
  TRAGEDY = "Tragedie",
  DARK_FANTASY = "Dark Fantasy",
  FANTASY = "Fantaisie",
  MYSTERY = "Mystere",
  PSYCHOLOGICAL = "Psychologique",
  ROMANCE = "Romance",
  THRILLER = "Thriller",
  ARTS_MARTIAUX = "Arts Martiaux",
  COMEDY = "Comedie",
  POLICE = "Policier",
  ECOLE = "Ecole",
}