export enum Genre {
  ACTION = "Action",
  AVENTURE = "Aventure",
  DRAMA = "Drame",
  SURNATURAL = "Surnaturel",
  HORROR = "Horreur",
  TRAGEDY = "Tragedie",
  DARK_FANTASY = "Dark Fantasy",
  FANTASY = "Fantaisie",
  MYSTERY = "Mystere",
  PSYCHOLOGICAL = "Psychologique",
  ROMANCE = "Romance",
  THRILLER = "Thriller",
  ARTS_MARTIAUX = "Arts Martiaux",
  COMEDY = "Comedie",
  POLICE = "Policier",
  ECOLE = "Ecole",
  HUMOUR = "Humour",
  SURREALISTIC = "Surrealiste",
  FANTASTIC = "Fantastique",
  PARODY = "Parodie",
  SCIENCE_FICTION = "Science Fiction",
  SUPER_HEROS = "Super Heros",
  SLICE_LIFE = "Tranche de vie",
  SPORT = "Sport",
  RECIT = "Recit",
  MUSICAL_COMEDY = "Comedie Musicale",


}